brew "git"
brew "go"
brew "opencode"
brew "postgresql@18", link: true, restart_service: true
brew "pnpm"
brew "stow"
brew "uv"
brew "vim"

cask "1password"
cask "1password-cli"
cask "caffeine"
cask "dbeaver-community"
cask "google-chrome"
cask "jagex"
cask "notunes"
cask "runelite"
cask "steam"
cask "visual-studio-code"

